package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnhLaptop generated by hbm2java
 */
@Entity
@Table(name="AnhLaptop"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class AnhLaptop  implements java.io.Serializable {


     private String id;
     private ChiTietSp chiTietSp;
     private String duongDan;

    public AnhLaptop() {
    }

	
    public AnhLaptop(String id) {
        this.id = id;
    }
    public AnhLaptop(String id, ChiTietSp chiTietSp, String duongDan) {
       this.id = id;
       this.chiTietSp = chiTietSp;
       this.duongDan = duongDan;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCTSP")
    public ChiTietSp getChiTietSp() {
        return this.chiTietSp;
    }
    
    public void setChiTietSp(ChiTietSp chiTietSp) {
        this.chiTietSp = chiTietSp;
    }

    
    @Column(name="DuongDan")
    public String getDuongDan() {
        return this.duongDan;
    }
    
    public void setDuongDan(String duongDan) {
        this.duongDan = duongDan;
    }




}


