package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChucVu generated by hbm2java
 */
@Entity
@Table(name="ChucVu"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class ChucVu  implements java.io.Serializable {


     private String id;
     private String ten;
     private Set<User> users = new HashSet<User>(0);

    public ChucVu() {
    }

	
    public ChucVu(String id) {
        this.id = id;
    }
    public ChucVu(String id, String ten, Set<User> users) {
       this.id = id;
       this.ten = ten;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chucVu")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


