package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cthd generated by hbm2java
 */
@Entity
@Table(name = "CTHD",
         schema = "dbo",
         catalog = "ProjectOne"
)
public class Cthd implements java.io.Serializable {

    @Column(name = "Id", unique = true, nullable = false, length = 10)
    @Id

    private String id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdCTSP")
    private ChiTietSp chiTietSp;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdHD")
    private HoaDon hoaDon;
    @Column(name = "soLuong")
    private int soLuong;
    @Column(name = "donGia", scale = 4)
    private BigDecimal donGia;
    @Column(name = "donGiaKhiGiam", scale = 4)
    private BigDecimal donGiaKhiGiam;
    @Column(name = "ThanhTien", scale = 4)
    private BigDecimal thanhTien;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cthd")
    private Set<Serial> serials = new HashSet<Serial>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cthd")
    private Set<PhieuBaoHanh> phieuBaoHanhs = new HashSet<PhieuBaoHanh>(0);

    public Cthd() {
    }

    public Cthd(String id, ChiTietSp chiTietSp, HoaDon hoaDon, int soLuong, BigDecimal donGia, BigDecimal thanhTien) {
        this.id = id;
        this.chiTietSp = chiTietSp;
        this.hoaDon = hoaDon;
        this.soLuong = soLuong;
        this.donGia = donGia;
        this.thanhTien = thanhTien;
    }

    public Cthd(String id, ChiTietSp chiTietSp, HoaDon hoaDon, int soLuong, BigDecimal donGia, BigDecimal donGiaKhiGiam, BigDecimal thanhTien) {
        this.id = id;
        this.chiTietSp = chiTietSp;
        this.hoaDon = hoaDon;
        this.soLuong = soLuong;
        this.donGia = donGia;
        this.donGiaKhiGiam = donGiaKhiGiam;
        this.thanhTien = thanhTien;
    }
    

    public Cthd(String id) {
        this.id = id;
    }

    public Cthd(String id, ChiTietSp chiTietSp, HoaDon hoaDon, int soLuong, BigDecimal donGia, BigDecimal donGiaKhiGiam, BigDecimal thanhTien, Set<Serial> serials, Set<PhieuBaoHanh> phieuBaoHanhs) {
        this.id = id;
        this.chiTietSp = chiTietSp;
        this.hoaDon = hoaDon;
        this.soLuong = soLuong;
        this.donGia = donGia;
        this.donGiaKhiGiam = donGiaKhiGiam;
        this.thanhTien = thanhTien;
        this.serials = serials;
        this.phieuBaoHanhs = phieuBaoHanhs;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ChiTietSp getChiTietSp() {
        return this.chiTietSp;
    }

    public void setChiTietSp(ChiTietSp chiTietSp) {
        this.chiTietSp = chiTietSp;
    }

    public HoaDon getHoaDon() {
        return this.hoaDon;
    }

    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }

    public int getSoLuong() {
        return this.soLuong;
    }

    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    public BigDecimal getDonGia() {
        return this.donGia;
    }

    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }

    public BigDecimal getDonGiaKhiGiam() {
        return this.donGiaKhiGiam;
    }

    public void setDonGiaKhiGiam(BigDecimal donGiaKhiGiam) {
        this.donGiaKhiGiam = donGiaKhiGiam;
    }

    public BigDecimal getThanhTien() {
        return this.thanhTien;
    }

    public void setThanhTien(BigDecimal thanhTien) {
        this.thanhTien = thanhTien;
    }

    public Set<Serial> getSerials() {
        return this.serials;
    }

    public void setSerials(Set<Serial> serials) {
        this.serials = serials;
    }

    public Set<PhieuBaoHanh> getPhieuBaoHanhs() {
        return this.phieuBaoHanhs;
    }

    public void setPhieuBaoHanhs(Set<PhieuBaoHanh> phieuBaoHanhs) {
        this.phieuBaoHanhs = phieuBaoHanhs;
    }

    @Override
    public String toString() {
        return "Cthd{" + "id=" + id + ", chiTietSp=" + chiTietSp + ", hoaDon=" + hoaDon + ", soLuong=" + soLuong + ", donGia=" + donGia + ", donGiaKhiGiam=" + donGiaKhiGiam + ", thanhTien=" + thanhTien + '}';
    }

}
