package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cthd generated by hbm2java
 */
@Entity
@Table(name="CTHD"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class Cthd  implements java.io.Serializable {


     private String id;
     private ChiTietSp chiTietSp;
     private HoaDon hoaDon;
     private int soLuong;
     private double donGia;
     private double donGiaKhiGiam;
     private double thanhTien;
     private Set<Serial> serials = new HashSet<Serial>(0);
     private Set<PhieuBaoHanh> phieuBaoHanhs = new HashSet<PhieuBaoHanh>(0);

    public Cthd() {
    }
     
    public Cthd(String id, ChiTietSp chiTietSp, HoaDon hoaDon, int soLuong, double donGia, double thanhTien) {
        this.id = id;
        this.chiTietSp = chiTietSp;
        this.hoaDon = hoaDon;
        this.soLuong = soLuong;
        this.donGia = donGia;
        this.thanhTien = thanhTien;
    }

	
    public Cthd(String id) {
        this.id = id;
    }
    public Cthd(String id, ChiTietSp chiTietSp, HoaDon hoaDon, int soLuong, double donGia, double donGiaKhiGiam, double thanhTien, Set<Serial> serials, Set<PhieuBaoHanh> phieuBaoHanhs) {
       this.id = id;
       this.chiTietSp = chiTietSp;
       this.hoaDon = hoaDon;
       this.soLuong = soLuong;
       this.donGia = donGia;
       this.donGiaKhiGiam = donGiaKhiGiam;
       this.thanhTien = thanhTien;
       this.serials = serials;
       this.phieuBaoHanhs = phieuBaoHanhs;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCTSP")
    public ChiTietSp getChiTietSp() {
        return this.chiTietSp;
    }
    
    public void setChiTietSp(ChiTietSp chiTietSp) {
        this.chiTietSp = chiTietSp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdHD")
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }

    
    @Column(name="soLuong")
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="donGia", scale=4)
    public double getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(double donGia) {
        this.donGia = donGia;
    }

    
    @Column(name="donGiaKhiGiam", scale=4)
    public double getDonGiaKhiGiam() {
        return this.donGiaKhiGiam;
    }
    
    public void setDonGiaKhiGiam(double donGiaKhiGiam) {
        this.donGiaKhiGiam = donGiaKhiGiam;
    }

    
    @Column(name="ThanhTien", scale=4)
    public double getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(double thanhTien) {
        this.thanhTien = thanhTien;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cthd")
    public Set<Serial> getSerials() {
        return this.serials;
    }
    
    public void setSerials(Set<Serial> serials) {
        this.serials = serials;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cthd")
    public Set<PhieuBaoHanh> getPhieuBaoHanhs() {
        return this.phieuBaoHanhs;
    }
    
    public void setPhieuBaoHanhs(Set<PhieuBaoHanh> phieuBaoHanhs) {
        this.phieuBaoHanhs = phieuBaoHanhs;
    }

    @Override
    public String toString() {
        return "Cthd{" + "id=" + id + ", chiTietSp=" + chiTietSp + ", hoaDon=" + hoaDon + ", soLuong=" + soLuong + ", donGia=" + donGia + ", donGiaKhiGiam=" + donGiaKhiGiam + ", thanhTien=" + thanhTien + '}';
    }




}


