package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DongSp generated by hbm2java
 */
@Entity
@Table(name="DongSP"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class DongSp  implements java.io.Serializable {


     private String id;
     private String ten;
     private Set<ChiTietSp> chiTietSps = new HashSet<ChiTietSp>(0);

    public DongSp() {
    }

	
    public DongSp(String id) {
        this.id = id;
    }
    public DongSp(String id, String ten, Set<ChiTietSp> chiTietSps) {
       this.id = id;
       this.ten = ten;
       this.chiTietSps = chiTietSps;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dongSp")
    public Set<ChiTietSp> getChiTietSps() {
        return this.chiTietSps;
    }
    
    public void setChiTietSps(Set<ChiTietSp> chiTietSps) {
        this.chiTietSps = chiTietSps;
    }

    @Override
    public String toString() {
        return ten ;
    }




}


