package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "HoaDon",
        schema = "dbo",
        catalog = "ProjectOne"
)
public class HoaDon implements java.io.Serializable {

    @Column(name = "Id", unique = true, nullable = false, length = 10)
    @Id

    private String id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdKH")
    private KhachHang khachHang;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdNV")
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idVoucher")
    private VoucherHd voucherHd;
    @Temporal(TemporalType.DATE)
    @Column(name = "NgayTao", length = 10)
    private Date ngayTao;
    @Temporal(TemporalType.DATE)
    @Column(name = "NgayThanhToan", length = 10)
    private Date ngayThanhToan;
    @Temporal(TemporalType.DATE)
    @Column(name = "NgayShip", length = 10)
    private Date ngayShip;
    @Temporal(TemporalType.DATE)
    @Column(name = "NgayNhan", length = 10)
    private Date ngayNhan;
    @Column(name = "TinhTrang")
    private int tinhTrang;
    @Column(name = "TenNguoiNhan")
    private String tenNguoiNhan;
    @Column(name = "DiaChi")
    private String diaChi;
    @Column(name = "Sdt", length = 30)
    private String sdt;
    @Column(name = "ThanhTien", scale = 4)
    private BigDecimal tongTien;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hoaDon")
    private Set<Cthd> cthds = new HashSet<Cthd>(0);

    public HoaDon() {
    }

    public HoaDon(String id, Date ngayTao) {
        this.id = id;
        this.ngayTao = ngayTao;
    }

    public HoaDon(String id) {
        this.id = id;
    }

    public HoaDon(String id, KhachHang khachHang, User user, VoucherHd voucherHd, Date ngayTao, Date ngayThanhToan, Date ngayShip, Date ngayNhan, int tinhTrang, String tenNguoiNhan, String diaChi, String sdt, Set<Cthd> cthds) {
        this.id = id;
        this.khachHang = khachHang;
        this.user = user;
        this.voucherHd = voucherHd;
        this.ngayTao = ngayTao;
        this.ngayThanhToan = ngayThanhToan;
        this.ngayShip = ngayShip;
        this.ngayNhan = ngayNhan;
        this.tinhTrang = tinhTrang;
        this.tenNguoiNhan = tenNguoiNhan;
        this.diaChi = diaChi;
        this.sdt = sdt;
        this.cthds = cthds;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public BigDecimal getTongTien() {
        return tongTien;
    }

    public void setTongTien(BigDecimal tongTien) {
        this.tongTien = tongTien;
    }

    public KhachHang getKhachHang() {
        return this.khachHang;
    }

    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public VoucherHd getVoucherHd() {
        return this.voucherHd;
    }

    public void setVoucherHd(VoucherHd voucherHd) {
        this.voucherHd = voucherHd;
    }

    public Date getNgayTao() {
        return this.ngayTao;
    }

    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    public Date getNgayThanhToan() {
        return this.ngayThanhToan;
    }

    public void setNgayThanhToan(Date ngayThanhToan) {
        this.ngayThanhToan = ngayThanhToan;
    }

    public Date getNgayShip() {
        return this.ngayShip;
    }

    public void setNgayShip(Date ngayShip) {
        this.ngayShip = ngayShip;
    }

    public Date getNgayNhan() {
        return this.ngayNhan;
    }

    public void setNgayNhan(Date ngayNhan) {
        this.ngayNhan = ngayNhan;
    }

    public int getTinhTrang() {
        return this.tinhTrang;
    }

    public void setTinhTrang(int tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

    public String getTenNguoiNhan() {
        return this.tenNguoiNhan;
    }

    public void setTenNguoiNhan(String tenNguoiNhan) {
        this.tenNguoiNhan = tenNguoiNhan;
    }

    public String getDiaChi() {
        return this.diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getSdt() {
        return this.sdt;
    }

    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    public Set<Cthd> getCthds() {
        return this.cthds;
    }

    public void setCthds(Set<Cthd> cthds) {
        this.cthds = cthds;
    }

    @Override
    public String toString() {
        return "HoaDon{" + "id=" + id + ", khachHang=" + khachHang + ", user=" + user + ", voucherHd=" + voucherHd + ", ngayTao=" + ngayTao + ", ngayThanhToan=" + ngayThanhToan + ", ngayShip=" + ngayShip + ", ngayNhan=" + ngayNhan + ", tinhTrang=" + tinhTrang + ", tenNguoiNhan=" + tenNguoiNhan + ", diaChi=" + diaChi + ", sdt=" + sdt + '}';
    }

}
