package domainmodels;
// Generated Dec 8, 2022 9:31:17 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ManHinh generated by hbm2java
 */
@Entity
@Table(name="ManHinh"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class ManHinh  implements java.io.Serializable {


     private String id;
     private String chip;
     private int trangThai;
     private Set<ChiTietSp> chiTietSps = new HashSet<ChiTietSp>(0);

    public ManHinh() {
    }

	
    public ManHinh(String id) {
        this.id = id;
    }
    public ManHinh(String id, String chip, int trangThai, Set<ChiTietSp> chiTietSps) {
       this.id = id;
       this.chip = chip;
       this.trangThai = trangThai;
       this.chiTietSps = chiTietSps;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Chip")
    public String getChip() {
        return this.chip;
    }
    
    public void setChip(String chip) {
        this.chip = chip;
    }

    
    @Column(name="TrangThai")
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="manHinh")
    public Set<ChiTietSp> getChiTietSps() {
        return this.chiTietSps;
    }
    
    public void setChiTietSps(Set<ChiTietSp> chiTietSps) {
        this.chiTietSps = chiTietSps;
    }




}


