package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhieuBaoHanh generated by hbm2java
 */
@Entity
@Table(name="PhieuBaoHanh"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class PhieuBaoHanh  implements java.io.Serializable {


     private String id;
     private Cthd cthd;
     private KhachHang khachHang;
     private Date ngayTao;
     private Date ngayhetHan;
     private int trangThai;

    public PhieuBaoHanh() {
    }

	
    public PhieuBaoHanh(String id) {
        this.id = id;
    }
    public PhieuBaoHanh(String id, Cthd cthd, KhachHang khachHang, Date ngayTao, Date ngayhetHan, int trangThai) {
       this.id = id;
       this.cthd = cthd;
       this.khachHang = khachHang;
       this.ngayTao = ngayTao;
       this.ngayhetHan = ngayhetHan;
       this.trangThai = trangThai;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdHDCT")
    public Cthd getCthd() {
        return this.cthd;
    }
    
    public void setCthd(Cthd cthd) {
        this.cthd = cthd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDKH")
    public KhachHang getKhachHang() {
        return this.khachHang;
    }
    
    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayTao", length=10)
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayhetHan", length=10)
    public Date getNgayhetHan() {
        return this.ngayhetHan;
    }
    
    public void setNgayhetHan(Date ngayhetHan) {
        this.ngayhetHan = ngayhetHan;
    }

    
    @Column(name="TrangThai")
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }




}


