package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import jdk.nashorn.internal.objects.annotations.Getter;
import jdk.nashorn.internal.objects.annotations.Setter;

/**
 * Serial generated by hbm2java
 */
@Entity
@Table(name = "serial",
         schema = "dbo",
         catalog = "ProjectOne"
)

public class Serial implements java.io.Serializable {

    
    @Column(name = "IMEI", unique = true, nullable = false, length = 36)
    @Id
    private String imei;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdCTSP")
    private ChiTietSp chiTietSp;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IdCTHD")
    private Cthd cthd;
    @Column(name = "TrangThai")
    private int trangThai;

    public Serial() {
    }

    public Serial(String imei) {
        this.imei = imei;
    }

    public Serial(String imei, ChiTietSp chiTietSp, Cthd cthd, int trangThai) {
        this.imei = imei;
        this.chiTietSp = chiTietSp;
        this.cthd = cthd;
        this.trangThai = trangThai;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public ChiTietSp getChiTietSp() {
        return this.chiTietSp;
    }

    public void setChiTietSp(ChiTietSp chiTietSp) {
        this.chiTietSp = chiTietSp;
    }

    public Cthd getCthd() {
        return this.cthd;
    }

    public void setCthd(Cthd cthd) {
        this.cthd = cthd;
    }

    public int getTrangThai() {
        return this.trangThai;
    }

    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

    @Override
    public String toString() {
        return "Serial{" + "imei=" + imei + ", chiTietSp=" + chiTietSp + ", cthd=" + cthd + ", trangThai=" + trangThai + '}';
    }

}
