package domainmodels;
// Generated Nov 19, 2022 2:49:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="`user`",schema="dbo"
    ,catalog="ProjectOne"
)
public class User  implements java.io.Serializable {


     private String id;
     private ChucVu chucVu;
     private String ten;
     private String gioiTinh;
     private Date ngaySinh;
     private String diaChi;
     private String sdt;
     private String matKhau;
     private int trangThai;
     private Set<AnhNv> anhNvs = new HashSet<AnhNv>(0);
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, ChucVu chucVu, String ten, String gioiTinh, Date ngaySinh, String diaChi, String sdt, String matKhau, int trangThai, Set<AnhNv> anhNvs, Set<HoaDon> hoaDons) {
       this.id = id;
       this.chucVu = chucVu;
       this.ten = ten;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
       this.sdt = sdt;
       this.matKhau = matKhau;
       this.trangThai = trangThai;
       this.anhNvs = anhNvs;
       this.hoaDons = hoaDons;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCV")
    public ChucVu getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(ChucVu chucVu) {
        this.chucVu = chucVu;
    }

    
    @Column(name="Ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="GioiTinh")
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgaySinh", length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="DiaChi")
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="Sdt", length=30)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    
    @Column(name="MatKhau")
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    
    @Column(name="TrangThai")
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<AnhNv> getAnhNvs() {
        return this.anhNvs;
    }
    
    public void setAnhNvs(Set<AnhNv> anhNvs) {
        this.anhNvs = anhNvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }

    @Override
    public String toString() {
        return ten;
    }




}


